"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
DATA_FILES = ['h.gif']
OPTIONS = {
    'packages': [],
    'iconfile': 'h.gif',
    'plist': {
        'CFBundLeDevelopmentRegion': 'English',
        ' CFBundleIdentifier': "com.Skylink.xxx",
        'CFBundleVersion': "1.0.0",
        'NSHumanReadableCopyright': "Copyright © 2021, ForCodeCoder, All Rights Reserved"
        }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
